In [1]:
import pandas as pd

df = pd.read_csv("parfumo_data_clean.csv", na_values="NA", keep_default_na=False, dtype={"Number": str})
df.shape

(59325, 13)

In [2]:
scent_cols = ["Main_Accords", "Top_Notes", "Middle_Notes", "Base_Notes"]
df = df.dropna(subset=scent_cols, how="all").reset_index(drop=True)
df.shape

(42115, 13)

In [3]:
df.head()

,Number,Name,Brand,Release_Year,Concentration,Rating_Value,Rating_Count,Main_Accords,Top_Notes,Middle_Notes,Base_Notes,Perfumers,URL
0,0071,Tidal Pool,CB I Hate Perfume,2004.0,NaN,NaN,NaN,NaN,Bergamot,French lavender,"Musk, Foulness",Harry Frémont,https://www.parfumo.com/Perfumes/CB_I_Hate_Per...
1,0154,Pumpkin Pie,CB I Hate Perfume,1998.0,NaN,NaN,NaN,"Green, Leathery, Chypre, Animal",NaN,NaN,NaN,NaN,https://www.parfumo.com/Perfumes/CB_I_Hate_Per...
2,02,Coco.Conut,W.Dressroom,NaN,NaN,NaN,NaN,NaN,Coconut,"Milk, Tonka bean","Amber, Musk, Vanilla",NaN,https://www.parfumo.com/Perfumes/W_Dressroom/0...
3,03,Baby Green Tea,W.Dressroom,NaN,NaN,NaN,NaN,NaN,"Basil, Bergamot, Lemon, Orange","Iris, Jasmine, Lily of the valley, Orchid, Rose","Amber, Musk",NaN,https://www.parfumo.com/Perfumes/W_Dressroom/0...
4,069,Wet Pavement London,CB I Hate Perfume,NaN,NaN,NaN,NaN,NaN,"Aquatic notes, Lemon, Tangerine, Charcoal","Amber, Cedarwood, Floral notes, Acridity","Leather, Oakmoss, Patchouli, Tonka bean, Sewer",NaN,https://www.parfumo.com/Perfumes/CB_I_Hate_Per...

In [5]:
df = df[["Name", "Brand", "Release_Year", "Main_Accords", "Top_Notes", "Middle_Notes", "Base_Notes", "Perfumers"]]

In [6]:
df.head()

,Name,Brand,Release_Year,Main_Accords,Top_Notes,Middle_Notes,Base_Notes,Perfumers
0,Tidal Pool,CB I Hate Perfume,2004.0,NaN,Bergamot,French lavender,"Musk, Foulness",Harry Frémont
1,Pumpkin Pie,CB I Hate Perfume,1998.0,"Green, Leathery, Chypre, Animal",NaN,NaN,NaN,NaN
2,Coco.Conut,W.Dressroom,NaN,NaN,Coconut,"Milk, Tonka bean","Amber, Musk, Vanilla",NaN
3,Baby Green Tea,W.Dressroom,NaN,NaN,"Basil, Bergamot, Lemon, Orange","Iris, Jasmine, Lily of the valley, Orchid, Rose","Amber, Musk",NaN
4,Wet Pavement London,CB I Hate Perfume,NaN,NaN,"Aquatic notes, Lemon, Tangerine, Charcoal","Amber, Cedarwood, Floral notes, Acridity","Leather, Oakmoss, Patchouli, Tonka bean, Sewer",NaN